### ISSUE TITLE
Ultrasone sensor uitlezen op de Raspberry pi

### ISSUE THREAD

**Issue by kew10** [KingAbad/Autonomous_Cart_2#18]

**Comment by ALi-Natiq** [comment]
er wordt een ultrasoon sensor gebruikt als sensor

**Comment by ALi-Natiq** [comment]
python wordt gebruikt als programmeertaal met pi (vervangt jetson nano)

**Comment by ALi-Natiq** [comment]
ik heb de ultrasonic sensor geprogrammeerd gebruik maken van raspberry pi 4.

`#!/usr/bin/python
#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
#|R|a|s|p|b|e|r|r|y|P|i|-|S|p|y|.|c|o|.|u|k|
#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
#
# ultrasonic_2.py
# Measure distance using an ultrasonic module
# in a loop.
#
# Author : Matt Hawkins
# Date   : 28/01/2013

# -----------------------
# Import required Python libraries
# -----------------------
import time
import RPi.GPIO as GPIO

# -----------------------
# Define some functions
# -----------------------

def measure():
  # This function measures a distance
  GPIO.output(GPIO_TRIGGER, True)
  time.sleep(0.00001)
  GPIO.output(GPIO_TRIGGER, False)
  start = time.time()

  while GPIO.input(GPIO_ECHO)==0:
    start = time.time()

  while GPIO.input(GPIO_ECHO)==1:
    stop = time.time()

  elapsed = stop-start
  distance = (elapsed * 34300)/2

  return distance

def measure_average():
  # This function takes 3 measurements and
  # returns the average.
  distance1=measure()
  time.sleep(0.1)
  distance2=measure()
  time.sleep(0.1)
  distance3=measure()
  distance = distance1 + distance2 + distance3
  distance = distance / 3
  return distance

# -----------------------
# Main Script
# -----------------------

# Use BCM GPIO references
# instead of physical pin numbers
GPIO.setmode(GPIO.BCM)

# Define GPIO to use on Pi
GPIO_TRIGGER = 23
GPIO_ECHO    = 24

print "Ultrasonic Measurement"

# Set pins as output and input
GPIO.setup(GPIO_TRIGGER,GPIO.OUT)  # Trigger
GPIO.setup(GPIO_ECHO,GPIO.IN)      # Echo

# Set trigger to False (Low)
GPIO.output(GPIO_TRIGGER, False)

# Wrap main content in a try block so we can
# catch the user pressing CTRL-C and run the
# GPIO cleanup function. This will also prevent
# the user seeing lots of unnecessary error
# messages.
try:

  while True:

    distance = measure_average()
    print "Distance : %.1f" % distance
    time.sleep(1)

except KeyboardInterrupt:
  # User pressed CTRL-C
  # Reset GPIO settings
  [GPIO.cleanup()`]()

![ultrasonic_pi1](https://user-images.githubusercontent.com/46653906/77472010-8f8c6c00-6e13-11ea-8ad0-cf0310d07509.jpg)
![ultrasonic_pi2](https://user-images.githubusercontent.com/46653906/77472086-b054c180-6e13-11ea-8e40-5c7dd8831efb.jpg)

[https://www.raspberrypi-spy.co.uk/2013/01/ultrasonic-distance-measurement-using-python-part-2/](url)

**Comment by ALi-Natiq** [comment]
De ultrasonic sensor is geprogrammeerd met raspberry pi 4 met python.

![ultrasonic_pi1](https://user-images.githubusercontent.com/46653906/77472698-98ca0880-6e14-11ea-8077-2999969234d1.jpg)
![ultrasonic_pi2](https://user-images.githubusercontent.com/46653906/77472703-9bc4f900-6e14-11ea-82f6-e305bec2ee97.jpg)

Sorce:
https://www.raspberrypi-spy.co.uk/2013/01/ultrasonic-distance-measurement-using-python-part-2/
